### ISSUE TITLE
DALEXverse 0.19.8 release summer 2019

### ISSUE THREAD

**Issue by pbiecek** [ModelOriented/dime#20]
DALEXverse 0.19.8 release summer 2019

# Integration

- [x] readability: vignettes
- [x] readability: NEWS
- [x] readability: DESCRIPTION
- [x] consistency: pkgdown website
- [x] consistency: entry at DrWhy.AI webpage

assigned: @pbiecek  

# Code review

- [x] consistency: names of functions 
- [x] consistency: names of files
- [x] consistency: names of variables in functions (local and global)
- [x] length: functions
- [x] readability: code (comments, constructions)

assigned: @maksymiuks 

# Feature review

- [x] readability: documentation (title, description, details)
- [x] readability: examples (relevant, complete, with comments)
- [x] reproducibility: tests (code coverage)
- [x] links to functions: \code 

assigned: @WojciechKretowicz

**Comment by maksymiuks** [comment]
I've finished R code review, here are my thoughts:

* https://github.com/ModelOriented/dime/blob/master/R/modelStudio.R#L139-L140
I recommend to check if new observation and data has columns in the same order
* https://github.com/ModelOriented/dime/blob/master/R/modelStudio.R#L142-L147
I think that `!is_y` is better than `is_y==FALSE`. Accordingly `names(!is_y)` instead of `names(is_y[is_y==FALSE])`
* Everywhere
`if (show_info)` instead of `if (show_info == TRUE)`
* https://github.com/ModelOriented/dime/blob/master/R/modelStudio.R#L259-L261
In my opinion those lines are unnecessary. I see setting `getOptions()` as default parameter for `options` as better solution
* Camel case in prepare.R functions

**Comment by WojciechKretowicz** [comment]
* there is no link to main vignette on github, there is only link to 'perk and features', i've got lost at the very beginning
* what is model studio, in my opinion you could tell that model studio is a function in your package, just at the top of the vignette
* in the **Wrap it into an explainer** paragraph deleting sixth column could be more explicite, while going through your examples in R session it is not a problem, however just reading them is a little bit confusing
* in my opinion *N* and *B* in the example in the main vignette should be deleted or be described
* big plus for those videos
* function getOptions is very confusing for me, when I was reading vignette i thought that this is R's getOption function, difference between those two object was clear for me after going to **Reference** site, i think you could change the name of it or write very explicitly that this is different function from getOption
* in my opinion in **Generates interactive studio to explain predictive model** there is no visible difference between `# S3 method for explainer` and `# S3 method for default`
* i think that parameter *x* in *modelStudio* could be changed into something more clear, especially that there is also parameter *y* that does not correspond to *x* in natural way
* i think that warnings in modelStudio should be suppressed
* in getOptions parameter margin_x is confusing for me
* in my opinion you could more clearly describe the *xx_\** parameters, after reading the vignette i cannot point their usage
* again warnings, this time in getOptions

**Comment by hbaniecki** [comment]
- suppressWarnings() all warnings from describe function
- make this as function parameter https://github.com/ModelOriented/dime/blob/master/R/modelStudio.R#L292

**Comment by pbiecek** [comment]
imho it's ready for CRAN
